/**
 * Paquete gui
 */
package gui;

/**
 *
 * @author Carlos Valenzuela
 */
public class DlgPrePartida extends javax.swing.JDialog {

    DlgPanelJuego dlgPanelJuego;
    DlgColores dlgColores;

    /**
     * Creates new form FrmPanelJuego
     *
     * @param parent
     * @param modal
     */
    public DlgPrePartida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        dlgPanelJuego = new DlgPanelJuego(parent, modal);
        dlgColores = new DlgColores(parent, modal);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        btnSolicitarInicio = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelJugador = new javax.swing.JLabel();
        jTextJugador1 = new javax.swing.JTextField();
        jLabelJugador1 = new javax.swing.JLabel();
        jTextJugador2 = new javax.swing.JTextField();
        jLabelJugador2 = new javax.swing.JLabel();
        jTextJugador3 = new javax.swing.JTextField();
        jLabelJugador3 = new javax.swing.JLabel();
        jTextJugador4 = new javax.swing.JTextField();
        lblJugador1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblJugador3 = new javax.swing.JLabel();
        lblJugador4 = new javax.swing.JLabel();

        setTitle("Creación de partida");

        jPanelFondo.setBackground(new java.awt.Color(132, 174, 220));
        jPanelFondo.setForeground(new java.awt.Color(255, 0, 0));

        btnSolicitarInicio.setBackground(new java.awt.Color(153, 0, 153));
        btnSolicitarInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSolicitarInicio.setForeground(new java.awt.Color(153, 0, 153));
        btnSolicitarInicio.setText("Solicitar inicio de partida");
        btnSolicitarInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSolicitarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarInicioActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelJugador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelJugador.setText("Jugador 1:");

        jTextJugador1.setEditable(false);
        jTextJugador1.setBackground(new java.awt.Color(255, 255, 255));
        jTextJugador1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextJugador1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelJugador1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelJugador1.setText("Jugador 2:");

        jTextJugador2.setEditable(false);
        jTextJugador2.setBackground(new java.awt.Color(255, 255, 255));
        jTextJugador2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextJugador2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelJugador2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelJugador2.setText("Jugador 3:");

        jTextJugador3.setEditable(false);
        jTextJugador3.setBackground(new java.awt.Color(255, 255, 255));
        jTextJugador3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextJugador3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelJugador3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelJugador3.setText("Jugador 4:");

        jTextJugador4.setEditable(false);
        jTextJugador4.setBackground(new java.awt.Color(255, 255, 255));
        jTextJugador4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextJugador4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblJugador1.setBackground(new java.awt.Color(102, 102, 255));
        lblJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rgb.png"))); // NOI18N
        lblJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblJugador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJugador1MouseClicked(evt);
            }
        });

        lblJugador2.setBackground(new java.awt.Color(102, 102, 255));
        lblJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rgb.png"))); // NOI18N
        lblJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblJugador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJugador2MouseClicked(evt);
            }
        });

        lblJugador3.setBackground(new java.awt.Color(102, 102, 255));
        lblJugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rgb.png"))); // NOI18N
        lblJugador3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblJugador3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJugador3MouseClicked(evt);
            }
        });

        lblJugador4.setBackground(new java.awt.Color(102, 102, 255));
        lblJugador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rgb.png"))); // NOI18N
        lblJugador4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblJugador4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJugador4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJugador)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jTextJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJugador1))
                    .addComponent(jLabelJugador1)
                    .addComponent(jLabelJugador2)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jTextJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJugador3))
                    .addComponent(jLabelJugador3)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jTextJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJugador4))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jTextJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJugador2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                        .addComponent(btnSolicitarInicio)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addContainerGap())))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSolicitarInicio)
                .addGap(112, 112, 112)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJugador1))
                .addGap(18, 18, 18)
                .addComponent(jLabelJugador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJugador2))
                .addGap(18, 18, 18)
                .addComponent(jLabelJugador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJugador3))
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addComponent(jLabelJugador3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblJugador4))
                .addContainerGap(7, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        dlgPanelJuego.show();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSolicitarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarInicioActionPerformed

    }//GEN-LAST:event_btnSolicitarInicioActionPerformed

    private void lblJugador1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJugador1MouseClicked
        dlgColores.show();
    }//GEN-LAST:event_lblJugador1MouseClicked

    private void lblJugador2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJugador2MouseClicked
        dlgColores.show();
    }//GEN-LAST:event_lblJugador2MouseClicked

    private void lblJugador3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJugador3MouseClicked
        dlgColores.show();
    }//GEN-LAST:event_lblJugador3MouseClicked

    private void lblJugador4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJugador4MouseClicked
        dlgColores.show();
    }//GEN-LAST:event_lblJugador4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSolicitarInicio;
    private javax.swing.JLabel jLabelJugador;
    private javax.swing.JLabel jLabelJugador1;
    private javax.swing.JLabel jLabelJugador2;
    private javax.swing.JLabel jLabelJugador3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JTextField jTextJugador1;
    private javax.swing.JTextField jTextJugador2;
    private javax.swing.JTextField jTextJugador3;
    private javax.swing.JTextField jTextJugador4;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblJugador4;
    // End of variables declaration//GEN-END:variables

}
