/**
 * Paquete gui
 */
package gui;

/**
 *
 * @author Carlos Valenzuela
 */
public class DlgSalaDeEspera extends javax.swing.JDialog {

    DlgPanelJuego dlgPanelJuego;

    /**
     * Creates new form FrmPanelJuego
     *
     * @param parent
     * @param modal
     */
    public DlgSalaDeEspera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        dlgPanelJuego = new DlgPanelJuego(parent, modal);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        btnSolicitarInicio = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelJugador = new javax.swing.JLabel();
        jTextJugador1 = new javax.swing.JTextField();
        jLabelJugador1 = new javax.swing.JLabel();
        jTextJugador2 = new javax.swing.JTextField();
        jLabelJugador2 = new javax.swing.JLabel();
        jTextJugador3 = new javax.swing.JTextField();
        jLabelJugador3 = new javax.swing.JLabel();
        jTextJugador4 = new javax.swing.JTextField();

        setTitle("Creación de partida");

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setForeground(new java.awt.Color(255, 0, 0));

        btnSolicitarInicio.setBackground(new java.awt.Color(0, 0, 0));
        btnSolicitarInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSolicitarInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnSolicitarInicio.setText("Solicitar inicio de partida");
        btnSolicitarInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSolicitarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarInicioActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelJugador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelJugador.setForeground(new java.awt.Color(0, 0, 0));
        jLabelJugador.setText("Jugador 1:");

        jTextJugador1.setEditable(false);
        jTextJugador1.setBackground(new java.awt.Color(255, 255, 255));
        jTextJugador1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextJugador1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelJugador1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelJugador1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelJugador1.setText("Jugador 2:");

        jTextJugador2.setEditable(false);
        jTextJugador2.setBackground(new java.awt.Color(255, 255, 255));
        jTextJugador2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextJugador2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelJugador2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelJugador2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelJugador2.setText("Jugador 3:");

        jTextJugador3.setEditable(false);
        jTextJugador3.setBackground(new java.awt.Color(255, 255, 255));
        jTextJugador3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextJugador3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelJugador3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelJugador3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelJugador3.setText("Jugador 4:");

        jTextJugador4.setEditable(false);
        jTextJugador4.setBackground(new java.awt.Color(255, 255, 255));
        jTextJugador4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextJugador4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJugador)
                    .addComponent(jTextJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJugador1)
                    .addComponent(jTextJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJugador2)
                    .addComponent(jTextJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJugador3)
                    .addComponent(jTextJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnSolicitarInicio))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnSalir)))
                .addGap(36, 36, 36))
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnSolicitarInicio)
                        .addGap(78, 78, 78)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFondoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelJugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelJugador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelJugador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelJugador3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        dlgPanelJuego.show();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSolicitarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarInicioActionPerformed

    }//GEN-LAST:event_btnSolicitarInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSolicitarInicio;
    private javax.swing.JLabel jLabelJugador;
    private javax.swing.JLabel jLabelJugador1;
    private javax.swing.JLabel jLabelJugador2;
    private javax.swing.JLabel jLabelJugador3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JTextField jTextJugador1;
    private javax.swing.JTextField jTextJugador2;
    private javax.swing.JTextField jTextJugador3;
    private javax.swing.JTextField jTextJugador4;
    // End of variables declaration//GEN-END:variables

}
