package gui;

import control.JugadoresDAO;
import dominio.ColorJ;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import util.ConversionColores;
import util.DibujadoTablero;
import util.Validaciones;
/**
 * 
 * @author Administrador
 */
public class FrmTablero extends javax.swing.JFrame {
    
    //Se crea variable estatica para dibujar en tablero. 
    private DibujadoTablero dibujar;
    private Validaciones valida = new Validaciones();
    private int clicks = 1;
    private int X1, Y1, X2, Y2;
    private Color color;
    /**
     * Metodo que inicializa el dibujado de tablero.
     *
     */
    public FrmTablero() {
        initComponents();
        this.setLocationRelativeTo(null);
        dibujar = new DibujadoTablero();
        dibujar.setBounds(5, 5, 690, 650);
        dibujar.addMouseListener(eventos);
        this.panelTablero.add(dibujar);
        this.dibujarTablero();
        this.establecerInfoJugadores();
    }
    /**
     * Este metodo se encarga de establecer la informacion de cada jugador 
     * (avatar,nombre,puntos y color) luego muestra los datos en el panel 
     * de los jugadores.
     */ 
    private void establecerInfoJugadores() {

        this.panelAvatarJ1.setIcon(JugadoresDAO.jugadores[0].getAvatar());
        this.nombreJ1.setText(JugadoresDAO.jugadores[0].getUsuario());
        this.puntosJ1.setText(JugadoresDAO.jugadores[0].getPuntuacion() + "");
        ColorJ colorJ1 = JugadoresDAO.jugadores[0].getColor();
        String hex1 = ConversionColores.conversionColorHex(colorJ1);
        this.colorJugador1.setBackground(Color.decode(hex1));

        this.panelAvatarJ2.setIcon(JugadoresDAO.jugadores[1].getAvatar());
        this.nombreJ2.setText(JugadoresDAO.jugadores[1].getUsuario());
        this.puntosJ2.setText(JugadoresDAO.jugadores[1].getPuntuacion() + "");
        ColorJ colorJ2 = JugadoresDAO.jugadores[1].getColor();
        String hex2 = ConversionColores.conversionColorHex(colorJ2);
        this.colorJugador2.setBackground(Color.decode(hex2));

        this.panelAvatarJ3.setIcon(JugadoresDAO.jugadores[2].getAvatar());
        this.nombreJ3.setText(JugadoresDAO.jugadores[2].getUsuario());
        this.puntosJ3.setText(JugadoresDAO.jugadores[2].getPuntuacion() + "");
        ColorJ colorJ3 = JugadoresDAO.jugadores[2].getColor();
        String hex3 = ConversionColores.conversionColorHex(colorJ3);
        this.colorJugador3.setBackground(Color.decode(hex3));

        this.panelAvatarJ4.setIcon(JugadoresDAO.jugadores[3].getAvatar());
        this.nombreJ4.setText(JugadoresDAO.jugadores[3].getUsuario());
        this.puntosJ4.setText(JugadoresDAO.jugadores[3].getPuntuacion() + "");
        ColorJ colorJ4 = JugadoresDAO.jugadores[3].getColor();
        String hex4 = ConversionColores.conversionColorHex(colorJ4);
        this.colorJugador4.setBackground(Color.decode(hex4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelJugadores = new javax.swing.JPanel();
        panelJ1 = new javax.swing.JPanel();
        avatarJ1 = new javax.swing.JPanel();
        panelAvatarJ1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        colorJugador1 = new javax.swing.JPanel();
        nombreJ1 = new javax.swing.JLabel();
        puntosJ1 = new javax.swing.JLabel();
        panelJ2 = new javax.swing.JPanel();
        avatarJ2 = new javax.swing.JPanel();
        panelAvatarJ2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        colorJugador2 = new javax.swing.JPanel();
        nombreJ2 = new javax.swing.JLabel();
        puntosJ2 = new javax.swing.JLabel();
        panelJ3 = new javax.swing.JPanel();
        avatarJ3 = new javax.swing.JPanel();
        panelAvatarJ3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        colorJugador3 = new javax.swing.JPanel();
        nombreJ3 = new javax.swing.JLabel();
        puntosJ3 = new javax.swing.JLabel();
        panelJ4 = new javax.swing.JPanel();
        avatarJ4 = new javax.swing.JPanel();
        panelAvatarJ4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        colorJugador4 = new javax.swing.JPanel();
        nombreJ4 = new javax.swing.JLabel();
        puntosJ4 = new javax.swing.JLabel();
        panelTablero = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAbandonar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tablero");
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        panelJugadores.setBackground(new java.awt.Color(255, 255, 255));

        panelJ1.setBackground(java.awt.Color.yellow);
        panelJ1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        avatarJ1.setBackground(new java.awt.Color(255, 255, 255));
        avatarJ1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        avatarJ1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout avatarJ1Layout = new javax.swing.GroupLayout(avatarJ1);
        avatarJ1.setLayout(avatarJ1Layout);
        avatarJ1Layout.setHorizontalGroup(
            avatarJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAvatarJ1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        avatarJ1Layout.setVerticalGroup(
            avatarJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avatarJ1Layout.createSequentialGroup()
                .addComponent(panelAvatarJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Puntuación: ");

        colorJugador1.setBackground(new java.awt.Color(204, 204, 204));
        colorJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorJugador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorJugador1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorJugador1Layout = new javax.swing.GroupLayout(colorJugador1);
        colorJugador1.setLayout(colorJugador1Layout);
        colorJugador1Layout.setHorizontalGroup(
            colorJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        colorJugador1Layout.setVerticalGroup(
            colorJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        nombreJ1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreJ1.setForeground(new java.awt.Color(51, 51, 51));
        nombreJ1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJ1.setText(".");

        puntosJ1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        puntosJ1.setForeground(new java.awt.Color(51, 51, 51));
        puntosJ1.setText("0");

        javax.swing.GroupLayout panelJ1Layout = new javax.swing.GroupLayout(panelJ1);
        panelJ1.setLayout(panelJ1Layout);
        panelJ1Layout.setHorizontalGroup(
            panelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJ1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(avatarJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJ1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(colorJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJ1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntosJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        panelJ1Layout.setVerticalGroup(
            panelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJ1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelJ1Layout.createSequentialGroup()
                        .addComponent(avatarJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreJ1))
                    .addGroup(panelJ1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puntosJ1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        panelJ2.setBackground(java.awt.Color.white);
        panelJ2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        avatarJ2.setBackground(new java.awt.Color(255, 255, 255));
        avatarJ2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        avatarJ2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout avatarJ2Layout = new javax.swing.GroupLayout(avatarJ2);
        avatarJ2.setLayout(avatarJ2Layout);
        avatarJ2Layout.setHorizontalGroup(
            avatarJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAvatarJ2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        avatarJ2Layout.setVerticalGroup(
            avatarJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avatarJ2Layout.createSequentialGroup()
                .addComponent(panelAvatarJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Puntuación: ");

        colorJugador2.setBackground(new java.awt.Color(204, 204, 204));
        colorJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorJugador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorJugador2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorJugador2Layout = new javax.swing.GroupLayout(colorJugador2);
        colorJugador2.setLayout(colorJugador2Layout);
        colorJugador2Layout.setHorizontalGroup(
            colorJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        colorJugador2Layout.setVerticalGroup(
            colorJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        nombreJ2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreJ2.setForeground(new java.awt.Color(51, 51, 51));
        nombreJ2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJ2.setText(".");

        puntosJ2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        puntosJ2.setForeground(new java.awt.Color(51, 51, 51));
        puntosJ2.setText("0");

        javax.swing.GroupLayout panelJ2Layout = new javax.swing.GroupLayout(panelJ2);
        panelJ2.setLayout(panelJ2Layout);
        panelJ2Layout.setHorizontalGroup(
            panelJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJ2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avatarJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJ2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(colorJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJ2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntosJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        panelJ2Layout.setVerticalGroup(
            panelJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJ2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelJ2Layout.createSequentialGroup()
                        .addComponent(avatarJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreJ2))
                    .addGroup(panelJ2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puntosJ2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        panelJ3.setBackground(java.awt.Color.white);
        panelJ3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        avatarJ3.setBackground(new java.awt.Color(255, 255, 255));
        avatarJ3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        avatarJ3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout avatarJ3Layout = new javax.swing.GroupLayout(avatarJ3);
        avatarJ3.setLayout(avatarJ3Layout);
        avatarJ3Layout.setHorizontalGroup(
            avatarJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAvatarJ3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        avatarJ3Layout.setVerticalGroup(
            avatarJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avatarJ3Layout.createSequentialGroup()
                .addComponent(panelAvatarJ3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Puntuación: ");

        colorJugador3.setBackground(new java.awt.Color(204, 204, 204));
        colorJugador3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorJugador3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorJugador3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorJugador3Layout = new javax.swing.GroupLayout(colorJugador3);
        colorJugador3.setLayout(colorJugador3Layout);
        colorJugador3Layout.setHorizontalGroup(
            colorJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        colorJugador3Layout.setVerticalGroup(
            colorJugador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        nombreJ3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreJ3.setForeground(new java.awt.Color(51, 51, 51));
        nombreJ3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJ3.setText(".");

        puntosJ3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        puntosJ3.setForeground(new java.awt.Color(51, 51, 51));
        puntosJ3.setText("0");

        javax.swing.GroupLayout panelJ3Layout = new javax.swing.GroupLayout(panelJ3);
        panelJ3.setLayout(panelJ3Layout);
        panelJ3Layout.setHorizontalGroup(
            panelJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJ3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avatarJ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreJ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJ3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(colorJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJ3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntosJ3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        panelJ3Layout.setVerticalGroup(
            panelJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJ3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelJ3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelJ3Layout.createSequentialGroup()
                        .addComponent(avatarJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreJ3))
                    .addGroup(panelJ3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puntosJ3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelJ4.setBackground(java.awt.Color.white);
        panelJ4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        avatarJ4.setBackground(new java.awt.Color(255, 255, 255));
        avatarJ4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        avatarJ4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout avatarJ4Layout = new javax.swing.GroupLayout(avatarJ4);
        avatarJ4.setLayout(avatarJ4Layout);
        avatarJ4Layout.setHorizontalGroup(
            avatarJ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAvatarJ4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        avatarJ4Layout.setVerticalGroup(
            avatarJ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avatarJ4Layout.createSequentialGroup()
                .addComponent(panelAvatarJ4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Puntuación: ");

        colorJugador4.setBackground(new java.awt.Color(204, 204, 204));
        colorJugador4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorJugador4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorJugador4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorJugador4Layout = new javax.swing.GroupLayout(colorJugador4);
        colorJugador4.setLayout(colorJugador4Layout);
        colorJugador4Layout.setHorizontalGroup(
            colorJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        colorJugador4Layout.setVerticalGroup(
            colorJugador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        nombreJ4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreJ4.setForeground(new java.awt.Color(51, 51, 51));
        nombreJ4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreJ4.setText(".");
        nombreJ4.setToolTipText("");

        puntosJ4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        puntosJ4.setForeground(new java.awt.Color(51, 51, 51));
        puntosJ4.setText("0");

        javax.swing.GroupLayout panelJ4Layout = new javax.swing.GroupLayout(panelJ4);
        panelJ4.setLayout(panelJ4Layout);
        panelJ4Layout.setHorizontalGroup(
            panelJ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJ4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avatarJ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreJ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelJ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJ4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelJ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(colorJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJ4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntosJ4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        panelJ4Layout.setVerticalGroup(
            panelJ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJ4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelJ4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelJ4Layout.createSequentialGroup()
                        .addComponent(avatarJ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreJ4))
                    .addGroup(panelJ4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puntosJ4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelJugadoresLayout = new javax.swing.GroupLayout(panelJugadores);
        panelJugadores.setLayout(panelJugadoresLayout);
        panelJugadoresLayout.setHorizontalGroup(
            panelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJugadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(panelJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelJ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJugadoresLayout.setVerticalGroup(
            panelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJugadoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelJ2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelJ3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelJ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelTablero.setBackground(new java.awt.Color(255, 255, 255));
        panelTablero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panelTablero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelTablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTableroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuAbandonar.setText("Opciones");

        jMenuItem1.setText("Abandonar partida");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAbandonar.add(jMenuItem1);

        jMenuBar1.add(jMenuAbandonar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorJugador2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorJugador2MouseClicked
        this.pantallaColores(JugadoresDAO.jugadores[1].getUsuario());
        this.cambiarColor("Jugador2");
    }//GEN-LAST:event_colorJugador2MouseClicked

    private void colorJugador3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorJugador3MouseClicked
        this.pantallaColores(JugadoresDAO.jugadores[2].getUsuario());
        this.cambiarColor("Jugador3");
    }//GEN-LAST:event_colorJugador3MouseClicked

    private void colorJugador4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorJugador4MouseClicked
        this.pantallaColores(JugadoresDAO.jugadores[3].getUsuario());
        this.cambiarColor("Jugador4");
    }//GEN-LAST:event_colorJugador4MouseClicked

    private void panelTableroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTableroMouseClicked
        this.coordenadaClick2(evt);
    }//GEN-LAST:event_panelTableroMouseClicked

    private void colorJugador1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorJugador1MouseClicked
        this.pantallaColores(JugadoresDAO.jugadores[0].getUsuario());
        this.cambiarColor("Jugador1");
    }//GEN-LAST:event_colorJugador1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        FrmPanelJuego menu = new FrmPanelJuego();
        menu.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /**
     * Pantalla que muestra el color de cada jugador.
     * 
     * @param jugador 
     */
    private void pantallaColores(String jugador) {
        DlgColores dlgColores = new DlgColores(this, true, jugador);
        dlgColores.setVisible(true);
    }

    /**
     * private void validaCoordenadas1(int x, int y) { //
     * System.out.println("entra"); int aux; //Coordenadas bien aplastadas if
     * ((x % 20) - 2 == 0 && (y % 16) - 2 == 0) { System.out.println(" ok"); }
     * else { //Error en coordenada x if ((x % 20) - 2 != 0) { //Cerca de un
     * punto a la derecha if (x % 20 > 10) { aux = 20 - (X1 % 20); X1 = X1 + aux
     * + 2; } else { aux = (x % 20) - 2; X1 = X1 - aux; } } //Error en
     * coordenada y if ((y % 16) - 2 != 0) { if (y % 16 > 8) { aux = 16 - (Y1 %
     * 16); Y1 = Y1 + aux + 2; System.out.println(aux); } else { aux = (y % 16)
     * - 2; Y1 = Y1 - aux; System.out.println(aux); } } }
     *
     * }
     *
     * private void validaCoordenadas2(int x, int y) { //
     * System.out.println("entra"); int aux; //Coordenadas bien aplastadas if
     * ((x % 20) - 2 == 0 && (y % 16) - 2 == 0) { System.out.println(" ok"); }
     * else { //Error en coordenada x if ((x % 20) - 2 != 0) { //Cerca de un
     * punto a la derecha if (x % 20 > 10) { aux = 20 - (X2 % 20); X2 = X2 + aux
     * + 2; } else { aux = (x % 20) - 2; X2 = X2 - aux; } } //Error en
     * coordenada y if ((y % 16) - 2 != 0) { if (y % 16 > 8) { aux = 16 - (Y2 %
     * 16); Y2 = Y2 + aux + 2; System.out.println(aux); } else { aux = (y % 16)
     * - 2; Y2 = Y2 - aux; System.out.println(aux); } } }
     *
     * }
     *
     */
    private void coordenadaClick1(java.awt.event.MouseEvent evt) {
        int arreglo[];
        this.X1 = evt.getX();
        this.Y1 = evt.getY();
        arreglo = valida.validaCoordenadas(X1, Y1);
        X1 = arreglo[0];
        Y1 = arreglo[1];
        System.out.println("\n" + X1 + "," + Y1);
    }
    /**
     * MouseEvent para validar las cordenadas en tablero.
     * 
     * @param evt 
     */
    private void coordenadaClick2(java.awt.event.MouseEvent evt) {
        int arreglo[];
        X2 = evt.getX();
        Y2 = evt.getY();
        arreglo = valida.validaCoordenadas(X2, Y2);
        X2 = arreglo[0];
        Y2 = arreglo[1];
        System.out.println(X2 + "," + Y2);
        int diferenciaX = Math.abs(X1 - X2);
        int diferenciaY = Math.abs(Y1 - Y2);
        System.out.println(diferenciaX);
        System.out.println(diferenciaY);
        if (diferenciaX > 20 || diferenciaY > 16 || (diferenciaX == 20 && diferenciaY == 16) || (diferenciaX == 0 && diferenciaY == 0)) {
            clicks = 1;
        } else {
            this.dibujar.dibujarLinea(X2, Y2, X1, Y1, (Graphics2D) dibujar.getGraphics(), color);
            clicks++;
        }

    }
    /**
     * Este metodo se encarga de cabiar el color de los jugadores. 
     * 
     * @param jugador 
     */
    private void cambiarColor(String jugador) {

        if (jugador.equals("Jugador1")) {
            String colorHex = ConversionColores.conversionColorHex(JugadoresDAO.jugadores[0].getColor());
            this.colorJugador1.setBackground(Color.decode(colorHex));
        }
        if (jugador.equals("Jugador2")) {
            String colorHex = ConversionColores.conversionColorHex(JugadoresDAO.jugadores[1].getColor());
            this.colorJugador2.setBackground(Color.decode(colorHex));
        }
        if (jugador.equals("Jugador3")) {
            String colorHex = ConversionColores.conversionColorHex(JugadoresDAO.jugadores[2].getColor());
            this.colorJugador3.setBackground(Color.decode(colorHex));
        }
        if (jugador.equals("Jugador4")) {
            String colorHex = ConversionColores.conversionColorHex(JugadoresDAO.jugadores[3].getColor());
            this.colorJugador4.setBackground(Color.decode(colorHex));
        }

    }
    //Se dibuja el tablero.
    private void dibujarTablero() {
        this.dibujar.paint((Graphics2D) this.panelTablero.getGraphics());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel avatarJ1;
    private javax.swing.JPanel avatarJ2;
    private javax.swing.JPanel avatarJ3;
    private javax.swing.JPanel avatarJ4;
    private javax.swing.JPanel colorJugador1;
    private javax.swing.JPanel colorJugador2;
    private javax.swing.JPanel colorJugador3;
    private javax.swing.JPanel colorJugador4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenuAbandonar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel nombreJ1;
    private javax.swing.JLabel nombreJ2;
    private javax.swing.JLabel nombreJ3;
    private javax.swing.JLabel nombreJ4;
    private javax.swing.JLabel panelAvatarJ1;
    private javax.swing.JLabel panelAvatarJ2;
    private javax.swing.JLabel panelAvatarJ3;
    private javax.swing.JLabel panelAvatarJ4;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelJ1;
    private javax.swing.JPanel panelJ2;
    private javax.swing.JPanel panelJ3;
    private javax.swing.JPanel panelJ4;
    private javax.swing.JPanel panelJugadores;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JLabel puntosJ1;
    private javax.swing.JLabel puntosJ2;
    private javax.swing.JLabel puntosJ3;
    private javax.swing.JLabel puntosJ4;
    // End of variables declaration//GEN-END:variables

    private MouseListener eventos = new MouseListener() {
        @Override
        public void mouseClicked(MouseEvent e) {
           
            if (clicks == 1) {
                coordenadaClick1(e);
                clicks++;
            } else {
                if (panelJ1.getBackground().equals(Color.YELLOW)) {
                    color = colorJugador1.getBackground();
                    coordenadaClick2(e);
                    if (clicks != 1) {
                        panelJ1.setBackground(Color.WHITE);
                        panelJ2.setBackground(Color.YELLOW);
                        clicks = 1;
                    }
                    return;
                }
                if (panelJ2.getBackground().equals(Color.YELLOW)) {
                    color = colorJugador2.getBackground();
                    coordenadaClick2(e);
                    if (clicks != 1) {
                        panelJ2.setBackground(Color.WHITE);
                        panelJ3.setBackground(Color.YELLOW);
                        clicks = 1;
                    }
                    return;
                }
                if (panelJ3.getBackground().equals(Color.YELLOW)) {
                    color = colorJugador3.getBackground();
                    coordenadaClick2(e);
                    if (clicks != 1) {
                        panelJ3.setBackground(Color.WHITE);
                        panelJ4.setBackground(Color.YELLOW);
                        clicks = 1;
                    }
                    return;

                }
                if (panelJ4.getBackground().equals(Color.YELLOW)) {
                    color = colorJugador4.getBackground();
                    coordenadaClick2(e);
                    if (clicks != 1) {
                        panelJ4.setBackground(Color.WHITE);
                        panelJ1.setBackground(Color.YELLOW);
                        clicks = 1;
                    }
                    return;
                }
            }
        }

        @Override

        public void mousePressed(MouseEvent e) {
        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
        }

    };

}
